### ISSUE TITLE
Setup commit lint

### ISSUE THREAD

**Issue by DHedgecock** [crystal-ball/commit-semantics#3]
### Goal

Ability to run `commitlint` after a commit message is finalized to ensure that it matches the required commitizen format

### Tasks

- [ ] Does `commitlint` have a preset for ESLint already?
- [ ] Can the Commit Lint Github app be configurable with a commit lint rc?
- [ ] Can Commit Lint Github app preference be changed without emailing support?
